services:
  frontend:
    image: bennybar35/myshop-frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
  backend:
    image: bennybar35/myshop-backend
    expose:
      - "3000"
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/myshop
  mongo:
    image: mongo:latest
    expose:
      - "27017"
    restart: always
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
